package org.scryption.view

import org.scryption.game.model.Card
import org.scryption.game.model.BoardPosition
import org.scryption.game.model.boardModel.Board
import org.scryption.game.model.events.{FightState, TurnState}
import org.scryption.game.model.managers.SacrificeManager
import org.scryption.{FightMessages, GameMessagesChannel}

import javax.swing.Timer
import scala.collection.mutable
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future
import scala.swing.Swing

class ViewModelFight(channel: GameMessagesChannel):

  private val eventQueue = mutable.Queue.empty[(FightState, TurnState)]
  private var isPlayingBack = false
  private var viewUpdateCallback: Option[(FightState, TurnState) => Unit] = None

  /** Starts the asynchronous listening of game states to synchronize them with the UI.
   *
   * @param onUpdate Callback invoked to apply the new game state and the new turn phase to the view.
   */
  def listenForUpdatedState(onUpdate: (FightState, TurnState) => Unit): Unit =
    viewUpdateCallback = Some(onUpdate)
    Future {
      while true do
        channel.receiveFromGame match
          case FightMessages.State(fightState, turn) =>
            Swing.onEDT {
              eventQueue.enqueue((fightState, turn))
              if !isPlayingBack then processNextEvent()
            }
          case _ =>
    }

  private def processNextEvent(): Unit =
    if eventQueue.isEmpty then
      isPlayingBack = false
    else
      isPlayingBack = true
      val (state, turn) = eventQueue.dequeue()
      viewUpdateCallback.foreach(_(state, turn))
      val delayMs = turn match
        case TurnState.playerFight => 2000
        case TurnState.botTurn     => 2000
        case TurnState.botFight    => 2000
        case _                     => 0
      if delayMs > 0 then
        val timer = new Timer(delayMs, _ => processNextEvent())
        timer.setRepeats(false)
        timer.start()
      else
        processNextEvent()

  /** Calculates the total amount of blood generated by the specified sacrifices on the board.
   *
   * @param board The current state of the board.
   * @param sacrificesPositions The list of coordinates of the cards chosen for sacrifice.
   * @return The total blood generated.
   */
  def calculateBlood(board: Board, sacrificesPositions: List[BoardPosition]): Int =
    SacrificeManager().resolveSacrifices(board, sacrificesPositions).generatedBlood

  /** Sends a request to play a card on a specific board column.
   *
   * @param card The card to be played.
   * @param position The column index where the card will be placed.
   */
  def cardToPlay(card: Card[?], position: Int): Unit =
    channel.sendToGame(FightMessages.CardToPlay(card, position))

  /** Sends a request to play a card by sacrificing the specified allied creatures.
   *
   * @param card The card to be played.
   * @param position The column index where the card will be placed.
   * @param sacrificesPositions The board coordinates of the sacrificed cards.
   */
  def cardToPlayWithSacrifices(card: Card[?], position: Int, sacrificesPositions: List[BoardPosition]): Unit =
    channel.sendToGame(FightMessages.CardToPlayWithSacrifices(card, position, sacrificesPositions))

  /** Sends a request to draw a Squirrel card.
   */
  def drawFromSquirrel() : Unit =
    channel.sendToGame(FightMessages.DrawFromSquirrel)

  /** Sends a request to use an item from the inventory.
   *
   * @param item The game item to use.
   * @param target The optional board position targeted by the item.
   */
  def useItem(item: org.scryption.game.model.items.GameItem, target: Option[BoardPosition] = None): Unit =
    channel.sendToGame(FightMessages.UseItem(item, target))

  /** Sends a request to draw a card from the main deck.
   */
  def drawFromDeck() : Unit =
    channel.sendToGame(FightMessages.DrawFromDeck)

  /** Sends a request to end the player's current turn.
   */
  def endTurn(): Unit =
    channel.sendToGame(FightMessages.EndPlayerTurn)
