name: Scala CI & Quality Checks

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    branches: [ "master", "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configuration
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: sbt Configuration
        uses: sbt/setup-sbt@v1

      - name: Checking Tests, format and Linter
        run: sbt checkAll